<?php

class ShopCategoryChildLogoSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //创建用户组
        DB::table('shop_categories')->insert(
        	array(
        		array(
		            'pid' => '28',
		            'name' => '衣物',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '28',
		            'name' => '鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '28',
		            'name' => '帽',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '28',
		            'name' => '袜',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '28',
		            'name' => '特殊鞋帽',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '28',
		            'name' => '婴儿',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '36',
		            'name' => '含酒精的饮料',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '68',
		            'name' => '羽绒服装',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '68',
		            'name' => '裤子',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '68',
		            'name' => '童装',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '68',
		            'name' => '内衣',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '68',
		            'name' => '睡衣',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '68',
		            'name' => '皮衣',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '68',
		            'name' => '衬衣',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '69',
		            'name' => '雨鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '69',
		            'name' => '运动鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '69',
		            'name' => '凉鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '69',
		            'name' => '拖鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '69',
		            'name' => '运动鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '69',
		            'name' => '足球鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '69',
		            'name' => '靴',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '70',
		            'name' => '帽',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '70',
		            'name' => '风帽',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '71',
		            'name' => '短袜',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '71',
		            'name' => '吊袜带',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '72',
		            'name' => '滑雪靴',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '72',
		            'name' => '体操鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '72',
		            'name' => '爬山鞋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '73',
		            'name' => '婴儿全套衣',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '73',
		            'name' => '婴儿睡袋',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '葡萄酒',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '果酒',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '米酒',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '黄酒',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '清酒',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '料酒',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '烧酒',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '鸡尾酒',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '74',
		            'name' => '白兰地',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	            array(
		            'pid' => '3',
		            'name' => '其他',
		            'slug'=> '',
		            'thumb'=>'',
		            'description' => '',
		            'level' => '0',
		            'sorts'  => '100',
		            'status'  => '1',
		            'created_at'  => '2015-01-15 10:10:10',
		            'updated_at'  => '2015-01-15 10:10:10',
	            ),
	        )
        );
    }

}
