<?php

class ShopFileSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //创建
        DB::table('files')->insert(
        	array(
        		array(
		            'disk_name' => 'shop1.png',
		            'file_name' => 'shop1.png',
		            'path'=> '/uploads/20150119/shop1.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop2.png',
		            'file_name' => 'shop2.png',
		            'path'=> '/uploads/20150119/shop2.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop3.png',
		            'file_name' => 'shop3.png',
		            'path'=> '/uploads/20150119/shop3.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop4.png',
		            'file_name' => 'shop4.png',
		            'path'=> '/uploads/20150119/shop4.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop5.png',
		            'file_name' => 'shop5.png',
		            'path'=> '/uploads/20150119/shop5.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop6.png',
		            'file_name' => 'shop6.png',
		            'path'=> '/uploads/20150119/shop6.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop7.png',
		            'file_name' => 'shop7.png',
		            'path'=> '/uploads/20150119/shop7.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop8.png',
		            'file_name' => 'shop8.png',
		            'path'=> '/uploads/20150119/shop8.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop9.png',
		            'file_name' => 'shop9.png',
		            'path'=> '/uploads/20150119/shop9.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop10.png',
		            'file_name' => 'shop10.png',
		            'path'=> '/uploads/20150119/shop10.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop11.png',
		            'file_name' => 'shop11.png',
		            'path'=> '/uploads/20150119/shop11.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'shop12.png',
		            'file_name' => 'shop12.png',
		            'path'=> '/uploads/20150119/shop12.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy1.png',
		            'file_name' => 'copy1.png',
		            'path'=> '/uploads/20150119/copy1.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy2.png',
		            'file_name' => 'copy2.png',
		            'path'=> '/uploads/20150119/copy2.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy3.png',
		            'file_name' => 'copy3.png',
		            'path'=> '/uploads/20150119/copy3.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy4.png',
		            'file_name' => 'copy4.png',
		            'path'=> '/uploads/20150119/copy4.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy5.png',
		            'file_name' => 'copy5.png',
		            'path'=> '/uploads/20150119/copy5.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy6.png',
		            'file_name' => 'copy6.png',
		            'path'=> '/uploads/20150119/copy6.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy7.png',
		            'file_name' => 'copy7.png',
		            'path'=> '/uploads/20150119/copy7.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy8.png',
		            'file_name' => 'copy8.png',
		            'path'=> '/uploads/20150119/copy8.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy9.png',
		            'file_name' => 'copy9.png',
		            'path'=> '/uploads/20150119/copy9.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy10.png',
		            'file_name' => 'copy10.png',
		            'path'=> '/uploads/20150119/copy10.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	            array(
		            'disk_name' => 'copy11.png',
		            'file_name' => 'copy11.png',
		            'path'=> '/uploads/20150119/copy11.png',
		            'size'=>'123',
		            'type' => 'image/png',
		            'created_at'  => '2015-01-15',
		            'updated_at'  => '2015-01-15',
	            ),
	        )
        );
    }

}
