<?php

class ShopCategoryLogoSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	//清除数据
    	DB::table('shop_categories')->delete();
        //创建用户组
        DB::table('shop_categories')->insert(
        	array(
        		array(
		            'pid' => '0',
		            'name' => '商标',
		            'slug'=> 'logo',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => '0',
		            'name' => '专利',
		            'slug'=> 'patent',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => '0',
		            'name' => '版权',
		            'slug'=> 'copy',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
        		array(
		            'pid' => 1,
		            'name' => '化学原料',
		            'slug'=> '01',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '颜料油漆',
		            'slug'=> '02',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '日化用品',
		            'slug'=> '03',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'10',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '燃料油脂',
		            'slug'=> '04',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '医用药品',
		            'slug'=> '05',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'4',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '金属材料',
		            'slug'=> '06',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '机械设备',
		            'slug'=> '07',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '手工器械',
		            'slug'=> '08',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '科学仪器',
		            'slug'=> '09',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'6',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '医疗器械',
		            'slug'=> '10',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '家用电器',
		            'slug'=> '11',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'7',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '运输工具',
		            'slug'=> '12',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '军火烟火',
		            'slug'=> '13',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '珠宝钟表',
		            'slug'=> '14',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'12',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '音乐器材',
		            'slug'=> '15',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '办公印刷',
		            'slug'=> '16',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '橡胶制品',
		            'slug'=> '17',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '皮革皮具',
		            'slug'=> '18',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'9',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '建筑金属',
		            'slug'=> '19',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '家具塑料',
		            'slug'=> '20',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>'11',
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '厨房陶瓷',
		            'slug'=> '21',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '绳网袋篷',
		            'slug'=> '22',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '纺织纱线',
		            'slug'=> '23',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '布料床单',
		            'slug'=> '24',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'13',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '服装鞋帽',
		            'slug'=> '25',
		            'thumb'=>'',
		            'level'=>2,
		            'sorts'=>1,
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '花边配饰',
		            'slug'=> '26',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '地毯席垫',
		            'slug'=> '27',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '健身娱乐',
		            'slug'=> '28',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '肉食蜜饯',
		            'slug'=> '29',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'3',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '小食配料',
		            'slug'=> '30',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'5',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '饲料花木',
		            'slug'=> '31',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '啤酒饮料',
		            'slug'=> '32',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '酒精饮料',
		            'slug'=> '33',
		            'thumb'=>'',
		            'level'=>2,
		            'sorts'=>2,
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '烟草烟具',
		            'slug'=> '34',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '广告销售',
		            'slug'=> '35',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '金融物管',
		            'slug'=> '36',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '建筑修理',
		            'slug'=> '37',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '通讯服务',
		            'slug'=> '38',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '运输贮藏',
		            'slug'=> '39',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '材料加工',
		            'slug'=> '40',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'14',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '教育娱乐',
		            'slug'=> '41',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '技术服务',
		            'slug'=> '42',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '餐饮住宿',
		            'slug'=> '43',
		            'thumb'=>'',
		            'level'=>1,
		            'sorts'=>'8',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '医疗园艺',
		            'slug'=> '44',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            ),
	            array(
		            'pid' => 1,
		            'name' => '社会服务',
		            'slug'=> '45',
		            'thumb'=>'',
		            'level'=>'',
		            'sorts'=>'100',
		            'status'=>1,
		            'description' => '',
		            'created_at'  => new DateTime,
		            'updated_at'  => new DateTime,
	            )
	        )
        );
    }

}
